version: "3"

services:
    php:
      image: php:8.1-fpm-alpine
      ports:
        - "9000:9000"

    adminer:
      image: adminer:latest
      ports:
        - "8080:8080"

    postgresql:
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      image: postgres:alpine

    nginx:
      image: nginx:stable-alpine
      ports:
        - "80:80"