version: "3"

services:
    adminer:
      image: adminer:4.8.1-standalone
      ports:
        - "${ADMINERPORT}:8080"

    postgresql:
      image: postgres:alpine
      ports:
        - "${POSTGRESPORT}:5432"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    nginx:
      image: nginx:stable-alpine
      ports:
        - "${NGINXPORT}:80"
      volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
      links:
        - php
    
    php:
      image: php:8.1-fpm-alpine
      volumes:
        - ./code:/code